In [11]:
import numpy as np
import plotly.graph_objects as go

fig = go.Figure(go.Scatter(x=[0,1,2,0], y=[0,2,0,0], fill="toself"))
fig.show()

In [28]:
a = np.array([[0,0,0,1,2,0,2,0,1],[0,0,0,-1,-2,0,-2,0,1]])
b1 = [0,3,6,0]
b2 = [1,4,7,1]
b3 = [2,5,8,2]
a1 = a[:,b1]
a2 = a[:,b2]
a3 = a[:,b3]

print('a1',a1,'a2',a2,'b3',a3)


a1 [[ 0  1  2  0]
 [ 0 -1 -2  0]] a2 [[ 0  2  0  0]
 [ 0 -2  0  0]] b3 [[0 0 1 0]
 [0 0 1 0]]


In [29]:
fig = go.Figure(go.Scatter3d(x=a1, y=a2, z = a3 ))
fig.show()

In [34]:
fig = go.Figure()
for i in range(0,a.shape[0]):
    
    fig.add_trace(go.Scatter3d(
    x=a1[i,:], y= a2[i,:], z=a3[i,:],
    marker=dict(
        size=4,
        color=1,
        colorscale='Viridis',
    ),
    line=dict(
        color='#1fb49b',
        width=1
    )
        ))

fig.show()






In [41]:
import pandas as pd
Coords = pd.read_csv('Out.csv')

In [42]:
Coords

Ox           Oy            Oz          Px           Py  \
0 -897.561431   264.670747 -6.200000e-07 -897.566118    64.670747   
1 -589.711025   378.590252 -5.607500e-04 -439.713055   291.986539   
2 -349.999921   344.974618  3.499999e+02 -279.289242   171.769538   
3  282.841971   759.806734 -7.071645e+01  369.960289   673.201851   
4    0.000008  1192.653266  2.902488e+02    0.000011  1292.649209   
5   -0.006470  1449.999978 -4.000065e+02 -100.008501  1623.203886   
6  526.150988  1501.148076  5.261510e+02  596.861661  1674.353158   
7 -212.137664  1452.628707  5.656861e+02 -125.020780  1539.232419   
8 -244.979601  1394.975626  3.240000e-06  -71.776863  1494.979683   
9 -189.711585  1071.409605  5.608000e-04  -39.711587   984.809406   

             Pz          Qx           Qy            Qz  
0 -8.400000e-07 -724.358774   164.666688 -4.700000e-07  
1  1.000015e+02 -439.711060   291.985388 -9.999846e+01  
2  2.792892e+02 -420.710550   171.769578  4.207106e+02  
3 -2.285454e+02  440.671137   846.408043 -1.578379e+02  
4  4.634562e+02    0.000011  1392.653196  2.902535e+02  
5 -4.000085e+02   99.991429  1623.206190 -4.000085e+02  
6  5.968617e+02  667.572296  1501.148119  6.675723e+02  
7  7.235166e+02  -54.307062  1366.028572  6.528061e+02  
8  4.010000e-06  -71.772218  1294.979753  9.000000e-07  
9 -1.000015e+02  -39.709592   984.808252  9.999846e+01

In [46]:
CoordArr = Coords.to_numpy()
CoordArr


(10, 9)

In [48]:
def Triangle_Plot(a,fig):
    
    b1 = [0,3,6,0]
    b2 = [1,4,7,1]
    b3 = [2,5,8,2]
    a1 = a[:,b1]
    a2 = a[:,b2]
    a3 = a[:,b3]

    for i in range(0,a.shape[0]):
    
        fig.add_trace(go.Scatter3d(
        x=a1[i,:], y= a2[i,:], z=a3[i,:],
        marker=dict(
            size=4,
            color=1,
            colorscale='Viridis',
        ),
        line=dict(
            color='#1fb49b',
            width=1
        )
            ))

    fig.show()

In [50]:
figur = go.Figure()
Triangle_Plot(CoordArr,figur)